CREATE TABLE Tokens (
    TokenId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Status TINYINT NOT NULL,
    CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSDATETIME(),
    ExpiresAt DATETIME2(3) NOT NULL,

    CONSTRAINT FK_Tokens_Users FOREIGN KEY (UserId)
        REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE INDEX IX_Tokens_UserId ON Tokens (UserId);
