CREATE TABLE Institutions_Ratings (
    InstitutionRatingId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    InstitutionId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NULL,
    Location TINYINT NOT NULL CHECK (Location BETWEEN 1 AND 5),
    Happiness TINYINT NOT NULL CHECK (Happiness BETWEEN 1 AND 5),
    Safety TINYINT NOT NULL CHECK (Safety BETWEEN 1 AND 5),
    Reputation TINYINT NOT NULL CHECK (Reputation BETWEEN 1 AND 5),
    Opportunities TINYINT NOT NULL CHECK (Opportunities BETWEEN 1 AND 5),
    Internet TINYINT NOT NULL CHECK (Internet BETWEEN 1 AND 5),
    Food TINYINT NOT NULL CHECK (Food BETWEEN 1 AND 5),
    Social TINYINT NOT NULL CHECK (Social BETWEEN 1 AND 5),
    Facilities TINYINT NOT NULL CHECK (Facilities BETWEEN 1 AND 5),
    Clubs TINYINT NOT NULL CHECK (Clubs BETWEEN 1 AND 5),
    Testimony NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2,
    Status TINYINT NOT NULL DEFAULT 1,

    FOREIGN KEY (InstitutionId) REFERENCES Institutions(InstitutionId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE SET NULL
);
