CREATE TABLE Institutions (
    InstitutionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    Description NVARCHAR(MAX),
    Province TINYINT NOT NULL,
    Type TINYINT NOT NULL,
    WebsiteUrl NVARCHAR(255),
    AiReviewSummary NVARCHAR(MAX),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2,
    Status TINYINT NOT NULL
);
