CREATE TABLE Teachers
(
    TeacherId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    Name NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    Biography NVARCHAR(MAX) NULL,
    AvatarUrl NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NOT NULL,
    Status TINYINT NOT NULL

    CONSTRAINT FK_Teachers_Users FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE SET NULL
);
